// The following files access `this` before calling `super()`,
// which is allowed in CoffeeScript but not in JavaScript.
const filesWithInvalidConstructors = [
  'app/common/session2.coffee',
  'app/sdk/actions/activateSignatureCardAction.coffee',
  'app/sdk/actions/applyCardToBoardAction.coffee',
  'app/sdk/actions/applyExhaustionAction.coffee',
  'app/sdk/actions/applyModifierAction.coffee',
  'app/sdk/actions/attackAction.coffee',
  'app/sdk/actions/bonusManaAction.coffee',
  'app/sdk/actions/bonusManaCoreAction.coffee',
  'app/sdk/actions/burnCardAction.coffee',
  'app/sdk/actions/cloneEntityAction.coffee',
  'app/sdk/actions/cloneEntityAsTransformAction.coffee',
  'app/sdk/actions/damageAction.coffee',
  'app/sdk/actions/damageAsAttackAction.coffee',
  'app/sdk/actions/dieAction.coffee',
  'app/sdk/actions/drawCardAction.coffee',
  'app/sdk/actions/drawStartingHandAction.coffee',
  'app/sdk/actions/drawToXCardsAction.coffee',
  'app/sdk/actions/endFollowupAction.coffee',
  'app/sdk/actions/endTurnAction.coffee',
  'app/sdk/actions/fightAction.coffee',
  'app/sdk/actions/forcedAttackAction.coffee',
  'app/sdk/actions/generateSignatureCardAction.coffee',
  'app/sdk/actions/healAction.coffee',
  'app/sdk/actions/hurtingDamageAction.coffee',
  'app/sdk/actions/killAction.coffee',
  'app/sdk/actions/moveAction.coffee',
  'app/sdk/actions/playCardAction.coffee',
  'app/sdk/actions/playCardAsTransformAction.coffee',
  'app/sdk/actions/playCardFromHandAction.coffee',
  'app/sdk/actions/playCardSilentlyAction.coffee',
  'app/sdk/actions/playSignatureCardAction.coffee',
  'app/sdk/actions/putCardInDeckAction.coffee',
  'app/sdk/actions/putCardInHandAction.coffee',
  'app/sdk/actions/randomDamageAction.coffee',
  'app/sdk/actions/randomPlayCardSilentlyAction.coffee',
  'app/sdk/actions/randomTeleportAction.coffee',
  'app/sdk/actions/refreshArtifactChargesAction.coffee',
  'app/sdk/actions/refreshExhaustionAction.coffee',
  'app/sdk/actions/removeAction.coffee',
  'app/sdk/actions/removeArtifactsAction.coffee',
  'app/sdk/actions/removeCardFromDeckAction.coffee',
  'app/sdk/actions/removeCardFromHandAction.coffee',
  'app/sdk/actions/removeManaCoreAction.coffee',
  'app/sdk/actions/removeModifierAction.coffee',
  'app/sdk/actions/removeRandomArtifactAction.coffee',
  'app/sdk/actions/replaceCardFromHandAction.coffee',
  'app/sdk/actions/resignAction.coffee',
  'app/sdk/actions/restoreChargeToAllArtifactsAction.coffee',
  'app/sdk/actions/restoreManaAction.coffee',
  'app/sdk/actions/revealHiddenCardAction.coffee',
  'app/sdk/actions/rollbackToSnapshotAction.coffee',
  'app/sdk/actions/setDamageAction.coffee',
  'app/sdk/actions/setExhaustionAction.coffee',
  'app/sdk/actions/startTurnAction.coffee',
  'app/sdk/actions/stopBufferingEventsAction.coffee',
  'app/sdk/actions/swapGeneralAction.coffee',
  'app/sdk/actions/swapUnitAllegianceAction.coffee',
  'app/sdk/actions/swapUnitsAction.coffee',
  'app/sdk/actions/takeAnotherTurnAction.coffee',
  'app/sdk/actions/teleportAction.coffee',
  'app/sdk/actions/teleportBehindUnitAction.coffee',
  'app/sdk/actions/teleportInFrontOfUnitAction.coffee',
  'app/sdk/actions/trueDamageAction.coffee',
  'app/sdk/actions/updateSignatureCardAction.coffee',
  'app/sdk/gameSession.coffee',
  'app/sdk/modifiers/modifierDoubleAttackStat.coffee',
  'app/sdk/modifiers/modifierDoubleHealthStat.coffee',
  'app/sdk/quests/questBeginnerCompleteSoloChallenges.coffee',
  'app/sdk/quests/questBeginnerFactionLevel.coffee',
  'app/sdk/quests/questBeginnerPlayOneQuickMatch.coffee',
  'app/sdk/quests/questBeginnerPlayPracticeGames.coffee',
  'app/sdk/quests/questBeginnerWinFourPracticeGames.coffee',
  'app/sdk/quests/questBeginnerWinOneSeasonGame.coffee',
  'app/sdk/quests/questBeginnerWinPracticeGames.coffee',
  'app/sdk/quests/questBeginnerWinThreeQuickMatches.coffee',
  'app/sdk/quests/questBeginnerWinThreeRankedMatches.coffee',
  'app/sdk/quests/questBeginnerWinTwoPracticeGames.coffee',
  'app/sdk/quests/questParticipationWithFaction.coffee',
  'app/sdk/quests/questWinWithFaction.coffee',
  'cli/analytics_cli.coffee',
  'cli/config.coffee',
  'cli/crm.coffee',
  'scripts/aws-utility/list-steal-time-servers.coffee',
  'scripts/aws-utility/turn-off-unused-maintenance-servers.coffee',
  'server/lib/custom_errors.coffee'
];

// Skip files with invalid constructor issues when decaffeinating.
const invalidConstructorFilter = function (path) {
  // Assumes '/duelyst/' only occurs in the path one time.
  const shortPath = path.split('/duelyst/')[1];
  if (filesWithInvalidConstructors.includes(shortPath)) {
    return false;
  }
  return true;
}

module.exports = {
  decaffeinateArgs: [
    '--disallow-invalid-constructors',
    '--keep-commonjs'
  ],
  jscodeshiftScripts: ['remove-coffee-from-imports.js'],
  fileFilterFn: invalidConstructorFilter
}
