/*
 * decaffeinate suggestions:
 * DS002: Fix invalid constructor
 * DS206: Consider reworking classes to avoid initClass
 * DS207: Consider shorter variations of null checks
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/main/docs/suggestions.md
 */
const TrueDamageAction = 		require('./trueDamageAction');
const _ = require('underscore');

/*
  Hurting damage actions are generated by the hurting phase of the game when a player has no more cards in the deck.
*/
class HurtingDamageAction extends TrueDamageAction {
	static initClass() {
		
			this.type ="HurtingDamageAction";
		
			this.prototype.damageAmount = 2;
		}

	constructor() {
		if (this.type == null) { this.type = HurtingDamageAction.type; }
		super(...arguments);
	}
}
HurtingDamageAction.initClass();

module.exports = HurtingDamageAction;
